# This section defines the build settings for the LIVE production site.
[build]
  base = "frontend/"
  command = "npm run build"
  publish = "dist/"

# This section tells Netlify where to find our backend serverless functions.
[functions]
  directory = "netlify/functions/"

# This section is the routing rule for our LIVE site's API.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/contact"
  status = 200

# This section is the instruction manual for the LOCAL 'netlify dev' command.
[dev]
  # This tells the Netlify CLI to run our master "dev" script.
  command = "npm run dev"
  targetPort = 5173
  functions = "netlify/functions"

