[build]
  # This tells Netlify to change its directory to 'frontend'
  base = "frontend/"
  
  # The commands to build our frontend
  command = "npm run build"
  publish = "dist/"

# --- THIS IS THE FIX ---
# We update the redirect to point to our new function name, 'contact'.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/contact"
  status = 200