[build]
  # --- THIS IS THE FINAL FIX ---
  # This tells Netlify to change its directory to 'frontend' BEFORE running any commands.
  base = "frontend/"
  
  # Now, these commands will run from inside the correct folder.
  command = "npm run build"
  publish = "frontend/dist"
  functions = "backend/"

[dev]
  command = "npm run dev"
  targetPort = 5173
  publish = "frontend/dist"