# This section defines the build settings for the LIVE production site.
[build]
  base = "frontend/"
  command = "npm run build"
  publish = "dist/"

# This section tells Netlify where to find our backend serverless functions.
[functions]
  directory = "netlify/functions/"

# This section is the routing rule for our LIVE site's API.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/contact"
  status = 200

# This section is the instruction manual for the LOCAL 'netlify dev' command.
[dev]
  # --- THE FINAL FIX ---
  # We tell the command to first change directory into 'frontend',
  # and THEN run the 'npm run dev' command.
  command = "cd frontend && npm run dev"
  targetPort = 5173
  functions = "netlify/functions"