# This section defines the build settings for the LIVE production site.
[build]
  # --- THE FINAL FIX ---
  # We combine install and build into one command to ensure it runs in the correct directory.
  command = "cd frontend && npm install && npm run build"
  # The publish directory is now a direct path from the root.
  publish = "frontend/dist/"

# This section tells Netlify where to find our backend serverless functions.
[functions]
  directory = "netlify/functions/"

# This section is the routing rule for our LIVE site's API.
# It will now work correctly.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/contact"
  status = 200

# --- THIS IS THE FINAL FIX ---
# This section is the instruction manual for the LOCAL 'netlify dev' command.
[dev]
  # This tells the command that our frontend is a Vite project.
  framework = "vite"
  # The command to start the Vite development server.
  command = "npm run dev"
  # The port that Vite runs on.
  targetPort = 5173
  # The folder where the function files are located.
  functions = "netlify/functions"