[build]
  # This tells Netlify to change its directory to 'frontend' BEFORE running any commands.
  base = "frontend/"
  
  # Since we are already inside 'frontend', the publish directory is simply 'dist'.
  command = "npm run build"
  publish = "dist/"
  
  # The functions directory is one level up from 'frontend', then into 'backend'.
  functions = "../backend/"

# --- THIS IS THE FINAL FIX ---
# This rule tells Netlify how to route API requests.
# It says: "Any request that starts with /api/, send it to our 'server' function."
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200