# This section defines the build settings for the LIVE production site.
[build]
  # We now run the build from the root, but tell it where to go.
  command = "cd frontend && npm run build"
  # The publish directory is now a direct path from the root.
  publish = "frontend/dist/"

# This section tells Netlify where to find our backend serverless functions.
[functions]
  directory = "netlify/functions/"

# This section is the routing rule for our LIVE site's API.
# It will now work correctly.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/contact"
  status = 200